### ISSUE TITLE
"Not a valid file" if path contains space

### ISSUE THREAD

**Issue by jobukkit** [thijsdejong/vscode-codam-norminette#5]
If you put your code in a folder with a space in the name, the plugin doesn't work.

![Screenshot](https://beeimg.com/images/w74227993573.png)

Here, the actual folder name is "Google Drive" but it discards everything in front of the space.

**Comment by thijsdejong** [comment]
@thijsdejong I have no time to fix this. Feel free to open a PR, I will review it ASAP.

**Comment by thijsdejong** [comment]
@jobukkit I have no time to work on this, feel free to submit a PR. I will review it ASAP.
